services:
  - type: web
    name: crosscut-service
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
